# Generated by Django 4.0.6 on 2022-08-13 16:57

import cloudinary.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('contact_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=60, null=True)),
                ('background_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'order_date',
            },
        ),
    ]
